# Generated by Django 4.0 on 2022-01-01 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.IntegerField()),
                ('nota', models.FloatField()),
                ('partial', models.CharField(max_length=500)),
                ('debug_data', models.CharField(max_length=1000)),
                ('submit_time', models.DateField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=False)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submits.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('atividade', models.IntegerField()),
                ('nota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submits.profile')),
            ],
        ),
    ]
