# Generated by Django 4.0 on 2022-01-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('submits', '0002_alter_notas_nota_id_alter_submission_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
