# Generated by Django 4.0 on 2022-01-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0003_alter_notas_nota_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
