# Generated by Django 4.0 on 2022-04-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0004_course_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.CharField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tags', models.CharField(max_length=500)),
                ('receiving_submissions', models.BooleanField()),
                ('template_script', models.CharField(max_length=500)),
                ('correction_script', models.CharField(max_length=500)),
                ('perfect_script', models.CharField(max_length=500)),
                ('errata', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='nota',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='user_model',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='nota',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_model',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='atividade',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submits.course'),
        ),
        migrations.AddField(
            model_name='grades',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submits.activity'),
        ),
        migrations.AddField(
            model_name='submission',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submits.activity'),
        ),
    ]
