# Generated by Django 4.0 on 2022-01-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0004_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='nota_id',
        ),
    ]
