# Generated by Django 4.0 on 2022-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0005_activity_rename_student_course_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='errata',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
