# Generated by Django 4.0 on 2022-04-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0006_alter_activity_errata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='errata',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
