# Generated by Django 4.0 on 2022-01-02 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0007_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.IntegerField()),
                ('nota', models.FloatField()),
                ('partial', models.CharField(max_length=500)),
                ('debug_data', models.CharField(max_length=1000)),
                ('submit_time', models.DateField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=False)),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submits.profile_info')),
            ],
        ),
    ]
