# Generated by Django 4.0 on 2022-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0008_alter_course_github_alter_course_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='template_script',
            field=models.FileField(storage='/t100', upload_to=''),
        ),
    ]
