# Generated by Django 4.0 on 2022-04-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0009_alter_activity_template_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='template_script',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
