# Generated by Django 4.0 on 2022-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0010_alter_activity_template_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='correction_script',
            field=models.FileField(upload_to='scripts/correction_scripts/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='perfect_script',
            field=models.FileField(upload_to='scripts/perfect_scripts/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='template_script',
            field=models.FileField(upload_to='scripts/template_scripts/'),
        ),
    ]
