# Generated by Django 4.0 on 2022-04-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0011_alter_activity_correction_script_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='inscriptions_open',
            new_name='subscription_open',
        ),
    ]
